version: '3.8'

services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    container_name: mongo-db
    volumes:
      - ./db/:/data/db
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    container_name: bia-challenge
    links:
      - mongodb
